[theme]

# Primary accent for interactive elements (set to a neutral gray)
primaryColor = '#000000'

# Background color for the main content area (white)
backgroundColor = '#FFFFFF'

# Background color for sidebar and most interactive widgets (light gray for subtle contrast)
secondaryBackgroundColor = '#F5F5F5'

# Color used for almost all text (black)
textColor = '#000000'

# Font family for all text in the app
font = "serif"
